In [3]:
import torch

In [4]:
x=torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [7]:
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [8]:
y.backward()

In [9]:
x.grad

tensor(6.)

In [10]:
x.grad.item()

6.0

In [11]:
y.grad

<ipython-input-11-10b3a7061f6d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [12]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [13]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [14]:
z=w*x+b

In [15]:
ypred=torch.sigmoid(z)

In [16]:
loss=torch.nn.functional.binary_cross_entropy(ypred,y)

In [17]:
loss.backward()

In [18]:
w.grad,b.grad

(tensor(6.6918), tensor(0.9988))

In [19]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [20]:
y=x.mean()

In [21]:
y.backward()

In [22]:
x.grad

tensor([0.3333, 0.3333, 0.3333])

In [23]:
y.backward()

In [24]:
x.grad # gradients accumualate

tensor([0.6667, 0.6667, 0.6667])

In [25]:
x.grad.zero_()

tensor([0., 0., 0.])

In [26]:
y.backward()

In [27]:
x.grad

tensor([0.3333, 0.3333, 0.3333])

In [28]:
x.requires_grad_(False) #off gradient tracking

tensor([1., 2., 3.])

In [29]:
x

tensor([1., 2., 3.])

In [30]:
y=x**2

In [31]:
y

tensor([1., 4., 9.])

In [32]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [39]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [40]:
y=x.detach() # do not track y gradients because it uses x without gradient

In [41]:
y

tensor([1., 2., 3.])

In [42]:
x

tensor([1., 2., 3.], requires_grad=True)

In [36]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [37]:
with torch.no_grad():
    y=x**2

In [38]:
y

tensor([1., 4., 9.])