In [2]:
import torch
import torch.nn as nn

In [4]:
features=torch.rand(10,5)

In [3]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

In [5]:
model=Model(features.shape[1])

In [6]:
model(features)

tensor([[0.5828],
        [0.6194],
        [0.4334],
        [0.5053],
        [0.5742],
        [0.5217],
        [0.5267],
        [0.5925],
        [0.5451],
        [0.5511]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[-0.3501,  0.1264,  0.2930, -0.4326,  0.1672]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([0.1814], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary

In [11]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [15]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [16]:
featutes=torch.rand(10,5)

In [17]:
model=Model(features.shape[1])

In [18]:
model(features)

tensor([[0.6510],
        [0.6481],
        [0.6427],
        [0.6454],
        [0.6461],
        [0.6425],
        [0.6448],
        [0.6449],
        [0.6468],
        [0.6491]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0623, -0.0630,  0.3178, -0.1533,  0.4456],
        [ 0.2821,  0.4150,  0.2476,  0.1010,  0.2251],
        [ 0.1131, -0.0835, -0.0675, -0.4329, -0.3451]], requires_grad=True)

In [21]:
model.linear1.bias

Parameter containing:
tensor([ 0.3578,  0.2101, -0.3280], requires_grad=True)

In [22]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0944, -0.0254,  0.2218]], requires_grad=True)

In [23]:
model.linear2.bias

Parameter containing:
tensor([0.5555], requires_grad=True)

In [24]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [28]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,features):
        out=self.network(features)
        return out

In [29]:
features=torch.rand(10,5)

In [30]:
model=Model(features.shape[1])

In [32]:
model(features)

tensor([[0.3529],
        [0.3705],
        [0.3522],
        [0.3678],
        [0.3622],
        [0.3577],
        [0.3571],
        [0.3521],
        [0.3686],
        [0.3698]], grad_fn=<SigmoidBackward0>)

In [64]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,LabelEncoder

In [65]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [66]:
df.shape

(569, 33)

In [67]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [68]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [69]:
xtrain,xtest,ytrain,ytest=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [70]:
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

In [71]:
ytrain[:10]

400    M
315    B
224    B
498    M
302    M
491    B
559    B
473    B
509    M
53     M
Name: diagnosis, dtype: object

In [72]:
encoder=LabelEncoder()
ytrain=encoder.fit_transform(ytrain)
ytest=encoder.transform(ytest)

In [73]:
ytrain[:10]

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [80]:
xtraintensor=torch.from_numpy(xtrain.astype(np.float32))
xtesttensor=torch.from_numpy(xtest.astype(np.float32))
ytraintensor=torch.from_numpy(ytrain.astype(np.float32))
ytesttensor=torch.from_numpy(ytest.astype(np.float32))

In [81]:
xtraintensor.shape

torch.Size([455, 30])

# Using built in feed forward network and activation

In [82]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    def lossfunction(self,ypred,y):
        eps=1e-7
        ypred=torch.clamp(ypred,eps,1-eps)
        loss=-(ytraintensor*torch.log(ypred)+(1-ytraintensor)*torch.log(1-ypred)).mean()
        return loss

In [83]:
lr=0.1
epochs=25

In [84]:
model=Model(xtraintensor.shape[1])

In [85]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=model.lossfunction(ypred,ytraintensor)
    loss.backward()
    with torch.no_grad():
        model.linear.weight-=lr*model.linear.weight.grad
        model.linear.bias-=lr*model.linear.bias.grad
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch: {epoch+1}, loss: {loss.item()}')   

epoch: 1, loss: 0.7444823980331421
epoch: 2, loss: 0.726164698600769
epoch: 3, loss: 0.7150368094444275
epoch: 4, loss: 0.7081089019775391
epoch: 5, loss: 0.7035113573074341
epoch: 6, loss: 0.7001881003379822
epoch: 7, loss: 0.6975781917572021
epoch: 8, loss: 0.6953911185264587
epoch: 9, loss: 0.6934769153594971
epoch: 10, loss: 0.6917552351951599
epoch: 11, loss: 0.6901814341545105
epoch: 12, loss: 0.6887282729148865
epoch: 13, loss: 0.6873778700828552
epoch: 14, loss: 0.6861175894737244
epoch: 15, loss: 0.6849376559257507
epoch: 16, loss: 0.6838306784629822
epoch: 17, loss: 0.6827899813652039
epoch: 18, loss: 0.6818102598190308
epoch: 19, loss: 0.68088698387146
epoch: 20, loss: 0.6800158619880676
epoch: 21, loss: 0.6791933178901672
epoch: 22, loss: 0.6784162521362305
epoch: 23, loss: 0.677681565284729
epoch: 24, loss: 0.6769867539405823
epoch: 25, loss: 0.6763290762901306


In [86]:
model.linear.weight

Parameter containing:
tensor([[-0.1286, -0.0249,  0.0103,  0.0262, -0.1289,  0.0238,  0.0702, -0.0530,
          0.0263,  0.1376,  0.0248,  0.0426, -0.0382,  0.0406, -0.1016, -0.0024,
         -0.0920,  0.0752,  0.0893, -0.0942,  0.1271,  0.0379, -0.0381,  0.0744,
          0.0809, -0.0790,  0.1185, -0.1600,  0.0041, -0.0094]],
       requires_grad=True)

In [87]:
model.linear.bias

Parameter containing:
tensor([-0.2184], requires_grad=True)

In [88]:
with torch.no_grad():
    ypred=model(xtesttensor)
    ypred=(ypred>0.9).float()
    acc=(ypred==ytesttensor).float().mean()
    print(f'acc :{acc}')

acc :0.6491228342056274


# Using buit in loss function

In [89]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

In [90]:
lossfunction=nn.BCELoss()

In [92]:
type(lossfunction)

torch.nn.modules.loss.BCELoss

In [93]:
model=Model(xtraintensor.shape[1])

In [94]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    # loss=model.lossfunction(ypred,ytraintensor)
    loss=lossfunction(ypred,ytraintensor)
    loss.backward()
    with torch.no_grad():
        model.linear.weight-=lr*model.linear.weight.grad
        model.linear.bias-=lr*model.linear.bias.grad
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch: {epoch+1}, loss: {loss.item()}')  

ValueError: Using a target size (torch.Size([455])) that is different to the input size (torch.Size([455, 1])) is deprecated. Please ensure they have the same size.

In [96]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=lossfunction(ypred,ytraintensor.view(-1,1))
    loss.backward()
    with torch.no_grad():
        model.linear.weight-=lr*model.linear.weight.grad
        model.linear.bias-=lr*model.linear.bias.grad
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch: {epoch+1}, loss: {loss.item()}') 

epoch: 1, loss: 0.5804843306541443
epoch: 2, loss: 0.45992588996887207
epoch: 3, loss: 0.39287009835243225
epoch: 4, loss: 0.3499174416065216
epoch: 5, loss: 0.3197251856327057
epoch: 6, loss: 0.29713529348373413
epoch: 7, loss: 0.279461532831192
epoch: 8, loss: 0.26516300439834595
epoch: 9, loss: 0.2532906234264374
epoch: 10, loss: 0.24322684109210968
epoch: 11, loss: 0.23455177247524261
epoch: 12, loss: 0.22696955502033234
epoch: 13, loss: 0.22026529908180237
epoch: 14, loss: 0.214278906583786
epoch: 15, loss: 0.20888850092887878
epoch: 16, loss: 0.2039993405342102
epoch: 17, loss: 0.19953685998916626
epoch: 18, loss: 0.19544102251529694
epoch: 19, loss: 0.19166338443756104
epoch: 20, loss: 0.1881638765335083
epoch: 21, loss: 0.1849093735218048
epoch: 22, loss: 0.18187206983566284
epoch: 23, loss: 0.17902840673923492
epoch: 24, loss: 0.17635837197303772
epoch: 25, loss: 0.17384469509124756


# Using built in optimization

In [97]:
model=Model(xtraintensor.shape[1])

In [102]:
optimizer=torch.optim.SGD(model.parameters(),lr=lr)

In [103]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=lossfunction(ypred,ytraintensor.view(-1,1))
    loss.backward()
    # with torch.no_grad():
    #     model.linear.weight-=lr*model.linear.weight.grad
    #     model.linear.bias-=lr*model.linear.bias.grad
    optimizer.step()
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    optimizer.zero_grad()
    print(f'epoch: {epoch+1}, loss: {loss.item()}') 

epoch: 1, loss: 0.6271464824676514
epoch: 2, loss: 0.5014553070068359
epoch: 3, loss: 0.4297850430011749
epoch: 4, loss: 0.3829320967197418
epoch: 5, loss: 0.34942084550857544
epoch: 6, loss: 0.32396575808525085
epoch: 7, loss: 0.3037910759449005
epoch: 8, loss: 0.28729143738746643
epoch: 9, loss: 0.27346888184547424
epoch: 10, loss: 0.2616673707962036
epoch: 11, loss: 0.2514362633228302
epoch: 12, loss: 0.2424546182155609
epoch: 13, loss: 0.23448674380779266
epoch: 14, loss: 0.22735543549060822
epoch: 15, loss: 0.22092436254024506
epoch: 16, loss: 0.21508677303791046
epoch: 17, loss: 0.20975759625434875
epoch: 18, loss: 0.20486822724342346
epoch: 19, loss: 0.20036248862743378
epoch: 20, loss: 0.19619394838809967
epoch: 21, loss: 0.19232377409934998
epoch: 22, loss: 0.1887192279100418
epoch: 23, loss: 0.1853523701429367
epoch: 24, loss: 0.18219934403896332
epoch: 25, loss: 0.17923948168754578


In [105]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=lossfunction(ypred,ytraintensor.view(-1,1))
    optimizer.zero_grad() #suggested
    loss.backward()
    optimizer.step()
    print(f'epoch: {epoch+1}, loss: {loss.item()}') 

epoch: 1, loss: 0.1764547973871231
epoch: 2, loss: 0.1738296002149582
epoch: 3, loss: 0.17135007679462433
epoch: 4, loss: 0.16900396347045898
epoch: 5, loss: 0.16678041219711304
epoch: 6, loss: 0.1646696925163269
epoch: 7, loss: 0.16266314685344696
epoch: 8, loss: 0.16075298190116882
epoch: 9, loss: 0.15893207490444183
epoch: 10, loss: 0.1571941375732422
epoch: 11, loss: 0.1555333286523819
epoch: 12, loss: 0.15394437313079834
epoch: 13, loss: 0.15242253243923187
epoch: 14, loss: 0.15096338093280792
epoch: 15, loss: 0.14956292510032654
epoch: 16, loss: 0.14821749925613403
epoch: 17, loss: 0.1469237208366394
epoch: 18, loss: 0.14567846059799194
epoch: 19, loss: 0.14447888731956482
epoch: 20, loss: 0.14332233369350433
epoch: 21, loss: 0.14220638573169708
epoch: 22, loss: 0.1411287486553192
epoch: 23, loss: 0.14008736610412598
epoch: 24, loss: 0.13908027112483978
epoch: 25, loss: 0.13810566067695618


In [112]:
with torch.no_grad():
    ypred=model(xtesttensor)
    ypred=(ypred>0.99).float()
    acc=(ypred==ytesttensor).float().mean()
    print(f'acc :{acc}')

acc :0.6151123642921448
