In [51]:
import torch
import torch.nn as nn

In [52]:
features=torch.rand(10,5)

In [53]:
features

tensor([[0.9708, 0.3268, 0.1478, 0.4662, 0.1140],
        [0.9115, 0.9927, 0.0045, 0.8559, 0.1197],
        [0.1156, 0.2163, 0.5893, 0.1457, 0.9718],
        [0.9915, 0.4237, 0.9760, 0.1703, 0.5064],
        [0.7897, 0.3186, 0.7539, 0.1534, 0.5793],
        [0.4653, 0.4031, 0.2220, 0.6388, 0.7879],
        [0.3176, 0.1549, 0.6340, 0.0875, 0.4920],
        [0.6475, 0.3401, 0.3847, 0.9845, 0.2963],
        [0.7191, 0.7050, 0.5622, 0.0393, 0.9897],
        [0.7517, 0.1553, 0.0978, 0.1170, 0.7536]])

In [54]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

In [55]:
model=Model(features.shape[1])

In [56]:
model(features)

tensor([[0.6150],
        [0.6996],
        [0.6106],
        [0.5842],
        [0.5885],
        [0.6524],
        [0.5875],
        [0.6472],
        [0.6327],
        [0.5974]], grad_fn=<SigmoidBackward0>)

In [57]:
model.linear.weight

Parameter containing:
tensor([[-0.1321,  0.3937, -0.1446,  0.2212,  0.0546]], requires_grad=True)

In [58]:
model.linear.bias

Parameter containing:
tensor([0.3799], requires_grad=True)

In [59]:
!pip install torchinfo

In [60]:
from torchinfo import summary

In [61]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [62]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [63]:
featutes=torch.rand(10,5)

In [64]:
model=Model(features.shape[1])

In [65]:
model(features)

tensor([[0.6309],
        [0.6267],
        [0.6228],
        [0.6220],
        [0.6242],
        [0.6301],
        [0.6228],
        [0.6238],
        [0.6314],
        [0.6434]], grad_fn=<SigmoidBackward0>)

In [66]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4093, -0.1528, -0.3712, -0.0526,  0.3513],
        [ 0.0226, -0.2810, -0.3200, -0.4043,  0.2974],
        [ 0.0369, -0.2658,  0.4290, -0.1480,  0.0912]], requires_grad=True)

In [67]:
model.linear1.bias

Parameter containing:
tensor([-0.1561, -0.0279, -0.1388], requires_grad=True)

In [68]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1994,  0.1608, -0.0341]], requires_grad=True)

In [69]:
model.linear2.bias

Parameter containing:
tensor([0.5059], requires_grad=True)

In [70]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [71]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,features):
        out=self.network(features)
        return out

In [72]:
features=torch.rand(10,5)

In [73]:
model=Model(features.shape[1])

In [74]:
model(features)

tensor([[0.4301],
        [0.4294],
        [0.4294],
        [0.4294],
        [0.4294],
        [0.4294],
        [0.4294],
        [0.4294],
        [0.4294],
        [0.4299]], grad_fn=<SigmoidBackward0>)

In [75]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,LabelEncoder

In [76]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [77]:
df.shape

(569, 33)

In [78]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [79]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [80]:
xtrain,xtest,ytrain,ytest=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [81]:
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

In [82]:
ytrain[:10]

487    M
111    B
504    B
62     M
116    B
218    M
518    B
397    B
193    M
155    B
Name: diagnosis, dtype: object

In [83]:
encoder=LabelEncoder()
ytrain=encoder.fit_transform(ytrain)
ytest=encoder.transform(ytest)

In [84]:
ytrain[:10]

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [85]:
xtraintensor=torch.from_numpy(xtrain.astype(np.float32))
xtesttensor=torch.from_numpy(xtest.astype(np.float32))
ytraintensor=torch.from_numpy(ytrain.astype(np.float32))
ytesttensor=torch.from_numpy(ytest.astype(np.float32))

In [86]:
xtraintensor.shape

torch.Size([455, 30])

# Using built in feed forward network and activation

In [87]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    def lossfunction(self,ypred,y):
        eps=1e-7
        ypred=torch.clamp(ypred,eps,1-eps)
        loss=-(ytraintensor*torch.log(ypred)+(1-ytraintensor)*torch.log(1-ypred)).mean()
        return loss

In [88]:
lr=0.1
epochs=25

In [89]:
model=Model(xtraintensor.shape[1])

In [90]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=model.lossfunction(ypred,ytraintensor)
    loss.backward()
    with torch.no_grad():
        model.linear.weight-=lr*model.linear.weight.grad
        model.linear.bias-=lr*model.linear.bias.grad
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch: {epoch+1}, loss: {loss.item()}')   

epoch: 1, loss: 0.7649906277656555
epoch: 2, loss: 0.7517240047454834
epoch: 3, loss: 0.7406613826751709
epoch: 4, loss: 0.7314643263816833
epoch: 5, loss: 0.7238182425498962
epoch: 6, loss: 0.7174412608146667
epoch: 7, loss: 0.7120898962020874
epoch: 8, loss: 0.7075608372688293
epoch: 9, loss: 0.7036882638931274
epoch: 10, loss: 0.7003399133682251
epoch: 11, loss: 0.6974118947982788
epoch: 12, loss: 0.6948227882385254
epoch: 13, loss: 0.692509651184082
epoch: 14, loss: 0.6904234886169434
epoch: 15, loss: 0.6885263919830322
epoch: 16, loss: 0.68678879737854
epoch: 17, loss: 0.6851873993873596
epoch: 18, loss: 0.6837037801742554
epoch: 19, loss: 0.6823233962059021
epoch: 20, loss: 0.6810342669487
epoch: 21, loss: 0.6798270344734192
epoch: 22, loss: 0.678693413734436
epoch: 23, loss: 0.6776266694068909
epoch: 24, loss: 0.6766213178634644
epoch: 25, loss: 0.6756724119186401


In [91]:
model.linear.weight

Parameter containing:
tensor([[ 0.0966, -0.0323,  0.0847, -0.0244,  0.1707, -0.0441,  0.0935,  0.0352,
          0.1235, -0.0694, -0.1104, -0.0300, -0.0572, -0.0010, -0.0575, -0.0748,
          0.0360,  0.1040,  0.0164, -0.0133,  0.0090,  0.0259, -0.1497,  0.0655,
         -0.1163, -0.0544,  0.0535, -0.1375,  0.0032,  0.0080]],
       requires_grad=True)

In [92]:
model.linear.bias

Parameter containing:
tensor([-0.2287], requires_grad=True)

In [93]:
with torch.no_grad():
    ypred=model(xtesttensor)
    ypred=(ypred>0.9).float()
    acc=(ypred==ytesttensor).float().mean()
    print(f'acc :{acc}')

acc :0.5964912176132202


# using built in loss

In [94]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

In [95]:
lossfunction=nn.BCELoss()

In [96]:
type(lossfunction)

torch.nn.modules.loss.BCELoss

In [97]:
model=Model(xtraintensor.shape[1])

In [106]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    # loss=model.lossfunction(ypred,ytraintensor)
    loss=lossfunction(ypred,ytraintensor)
    loss.backward()
    with torch.no_grad():
        model.linear.weight-=lr*model.linear.weight.grad
        model.linear.bias-=lr*model.linear.bias.grad
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch: {epoch+1}, loss: {loss.item()}')  

ValueError: Using a target size (torch.Size([455])) that is different to the input size (torch.Size([455, 1])) is deprecated. Please ensure they have the same size.

In [107]:
ytraintensor.shape

torch.Size([455])

In [108]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=lossfunction(ypred,ytraintensor.view(-1,1))
    loss.backward()
    with torch.no_grad():
        model.linear.weight-=lr*model.linear.weight.grad
        model.linear.bias-=lr*model.linear.bias.grad
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    print(f'epoch: {epoch+1}, loss: {loss.item()}') 

epoch: 1, loss: 0.17248967289924622
epoch: 2, loss: 0.16970674693584442
epoch: 3, loss: 0.16708749532699585
epoch: 4, loss: 0.16461677849292755
epoch: 5, loss: 0.16228125989437103
epoch: 6, loss: 0.1600692868232727
epoch: 7, loss: 0.15797045826911926
epoch: 8, loss: 0.1559755653142929
epoch: 9, loss: 0.15407641232013702
epoch: 10, loss: 0.15226566791534424
epoch: 11, loss: 0.15053676068782806
epoch: 12, loss: 0.14888377487659454
epoch: 13, loss: 0.1473013460636139
epoch: 14, loss: 0.1457846462726593
epoch: 15, loss: 0.1443292796611786
epoch: 16, loss: 0.1429312378168106
epoch: 17, loss: 0.14158694446086884
epoch: 18, loss: 0.14029298722743988
epoch: 19, loss: 0.1390463411808014
epoch: 20, loss: 0.13784421980381012
epoch: 21, loss: 0.13668406009674072
epoch: 22, loss: 0.13556347787380219
epoch: 23, loss: 0.13448023796081543
epoch: 24, loss: 0.13343238830566406
epoch: 25, loss: 0.13241802155971527


# Using built in optimization

In [109]:
model=Model(xtraintensor.shape[1])

In [110]:
optimizer=torch.optim.SGD(model.parameters(),lr=lr)

In [111]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=lossfunction(ypred,ytraintensor.view(-1,1))
    loss.backward()
    # with torch.no_grad():
    #     model.linear.weight-=lr*model.linear.weight.grad
    #     model.linear.bias-=lr*model.linear.bias.grad
    optimizer.step()
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    optimizer.zero_grad()
    print(f'epoch: {epoch+1}, loss: {loss.item()}') 

epoch: 1, loss: 0.5071561336517334
epoch: 2, loss: 0.42653533816337585
epoch: 3, loss: 0.37512341141700745
epoch: 4, loss: 0.3390626311302185
epoch: 5, loss: 0.3121100664138794
epoch: 6, loss: 0.29103732109069824
epoch: 7, loss: 0.27400079369544983
epoch: 8, loss: 0.25986769795417786
epoch: 9, loss: 0.24790167808532715
epoch: 10, loss: 0.23760193586349487
epoch: 11, loss: 0.22861546277999878
epoch: 12, loss: 0.22068554162979126
epoch: 13, loss: 0.2136206328868866
epoch: 14, loss: 0.2072746902704239
epoch: 15, loss: 0.20153409242630005
epoch: 16, loss: 0.19630910456180573
epoch: 17, loss: 0.19152753055095673
epoch: 18, loss: 0.1871308535337448
epoch: 19, loss: 0.18307077884674072
epoch: 20, loss: 0.17930711805820465
epoch: 21, loss: 0.17580623924732208
epoch: 22, loss: 0.1725395917892456
epoch: 23, loss: 0.1694827675819397
epoch: 24, loss: 0.1666148155927658
epoch: 25, loss: 0.16391757130622864


In [112]:
for epoch in range(epochs):
    ypred=model(xtraintensor)
    loss=lossfunction(ypred,ytraintensor.view(-1,1))
    optimizer.zero_grad() #suggested
    loss.backward()
    optimizer.step()
    print(f'epoch: {epoch+1}, loss: {loss.item()}') 

epoch: 1, loss: 0.1613752394914627
epoch: 2, loss: 0.15897399187088013
epoch: 3, loss: 0.15670163929462433
epoch: 4, loss: 0.15454739332199097
epoch: 5, loss: 0.15250171720981598
epoch: 6, loss: 0.15055608749389648
epoch: 7, loss: 0.14870283007621765
epoch: 8, loss: 0.1469351351261139
epoch: 9, loss: 0.14524681866168976
epoch: 10, loss: 0.14363230764865875
epoch: 11, loss: 0.14208655059337616
epoch: 12, loss: 0.14060495793819427
epoch: 13, loss: 0.13918332755565643
epoch: 14, loss: 0.1378178894519806
epoch: 15, loss: 0.1365051120519638
epoch: 16, loss: 0.1352418214082718
epoch: 17, loss: 0.13402506709098816
epoch: 18, loss: 0.13285213708877563
epoch: 19, loss: 0.13172054290771484
epoch: 20, loss: 0.13062797486782074
epoch: 21, loss: 0.1295723170042038
epoch: 22, loss: 0.12855158746242523
epoch: 23, loss: 0.127563938498497
epoch: 24, loss: 0.12660767138004303
epoch: 25, loss: 0.12568122148513794


In [118]:
with torch.no_grad():
    ypred=model(xtesttensor)
    ypred=(ypred>0.9999999).float()
    acc=(ypred==ytesttensor).float().mean()
    print(f'acc :{acc}')

acc :0.5964912176132202
