In [34]:
#importing torch
import torch

In [35]:
# how to see the version of pytorch
torch.__version__

'2.4.1+cu121'

In [36]:
# Creating a 0-dimensional tensor (scalar)
scalar_tensor = torch.tensor(42)

print(scalar_tensor)  # Output: tensor(42)
print(scalar_tensor.ndim)  # Output: 0

tensor(42)
0


In [37]:
# 1 dimension tensor
zero=torch.tensor([1])

In [38]:
zero.ndim

1

In [39]:
zero.ndimension()

1

In [40]:
zero.shape

torch.Size([1])

In [41]:
# 1 dimension tensor
zero=torch.tensor([1,2])

In [42]:
zero.shape

torch.Size([2])

In [43]:
zero.ndim

1

In [44]:
type(zero)

torch.Tensor

In [45]:
# how to see if gpu is avaliable
if torch.cuda.is_available():
    print(f'gpu :{torch.cuda.get_device_name(0)}')
else:
    print('cpu')

cpu


In [49]:
# it can be any value previously present in the menory
torch.empty(2,3)

tensor([[-8.6215e+34,  3.2509e-41, -8.6243e+34],
        [ 3.2509e-41,  0.0000e+00,  0.0000e+00]])

In [50]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [51]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [52]:
torch.rand(2,3)

tensor([[0.9962, 0.4600, 0.7638],
        [0.3413, 0.8964, 0.6838]])

In [53]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [58]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [59]:
single=torch.tensor([[1,2,3],[4,5,6]])

In [76]:
single

tensor([[1, 2, 3],
        [4, 5, 6]])

In [61]:
single.shape

torch.Size([2, 3])

In [62]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [64]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [66]:
# can be used to make an identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [70]:
# can be used to make an matrix of desired shape and fill any constant value
torch.full((3,3),2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [71]:
torch.empty_like(single)

tensor([[134299072408976,  99643132487488,  99643132585344],
        [ 99643132487008,               0,  99643089118416]])

In [72]:
torch.zeros_like(single)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [73]:
torch.ones_like(single)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [77]:
torch.rand_like(single)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [78]:
torch.rand_like(single,dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [79]:
single.dtype

torch.int64

In [80]:
torch.tensor(single,dtype=torch.float32)

<ipython-input-80-8615d7b73341>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(single,dtype=torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [81]:
single.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [82]:
single.dtype

torch.int64

In [86]:
single=single.to(torch.float32)

In [87]:
single.dtype

torch.float32

In [83]:
double=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]],dtype=torch.float32)

In [84]:
double

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [85]:
double.shape

torch.Size([2, 2, 2])

In [88]:
x=torch.rand(2,2)

In [89]:
x+2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [90]:
x-2

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

In [91]:
x*2

tensor([[1.7388, 1.1354],
        [1.4822, 0.8588]])

In [92]:
x/2

tensor([[0.4347, 0.2839],
        [0.3705, 0.2147]])

In [93]:
(x*100)//2

tensor([[43., 28.],
        [37., 21.]])

In [94]:
x%2

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [95]:
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

In [96]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [97]:
a+b

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])

In [98]:
a-b

tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])

In [99]:
a*b

tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])

In [100]:
a/b

tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])

In [101]:
a**b

tensor([[0.9645, 0.6301, 0.8700],
        [0.8820, 0.6248, 0.8495]])

In [102]:
a%b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [103]:
c=torch.tensor([-1,-2,-3,-4])

In [104]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [105]:
torch.neg(c)

tensor([1, 2, 3, 4])

In [106]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [107]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [108]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [109]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [110]:
torch.clamp(d,2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [111]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [112]:
torch.sum(e)

tensor(32.)

in torch dimension 0 is the column dimension

In [113]:
torch.sum(e,dim=0)

tensor([ 7., 14., 11.])

In [114]:
torch.sum(e,dim=1)

tensor([18., 14.])

In [115]:
torch.mean(e)

tensor(5.3333)

In [116]:
torch.mean(e,0)

tensor([3.5000, 7.0000, 5.5000])

In [117]:
torch.median(e)

tensor(5.)

In [118]:
torch.max(e)

tensor(9.)

In [119]:
torch.max(e,0)

torch.return_types.max(
values=tensor([7., 9., 9.]),
indices=tensor([0, 0, 1]))

torch.max with dimension return tuple of value aand indices

In [120]:
torch.prod(e)

tensor(0.)

In [121]:
torch.prod(e,0)

tensor([ 0., 45., 18.])

In [122]:
torch.std(e)

tensor(3.7238)

In [123]:
torch.var(e)

tensor(13.8667)

In [124]:
3.3912**2

11.50023744

In [128]:
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [125]:
torch.argmax(e)

tensor(1)

In [126]:
torch.argmax(e,0)

tensor([0, 0, 1])

In [127]:
torch.argmin(e)

tensor(3)

In [129]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
f,g

(tensor([[3, 4, 9],
         [6, 2, 0]]),
 tensor([[6, 2],
         [7, 9],
         [7, 3]]))

In [131]:
torch.matmul(f,g)

tensor([[109,  69],
        [ 50,  30]])

In [132]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])
vec1,vec2

(tensor([1, 2]), tensor([3, 4]))

In [133]:
torch.dot(vec1,vec2)

tensor(11)

In [134]:
torch.matmul(vec1,vec2)

tensor(11)

In [136]:
f

tensor([[3, 4, 9],
        [6, 2, 0]])

In [135]:
torch.transpose(f,0,1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [137]:
f.t()

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [138]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [139]:
torch.det(h)

tensor(-222.)

In [140]:
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

In [141]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
i,j

(tensor([[9., 5., 4.],
         [8., 8., 6.]]),
 tensor([[0., 0., 0.],
         [0., 1., 3.]]))

In [142]:
i>j

tensor([[True, True, True],
        [True, True, True]])

In [143]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [144]:
i>=j

tensor([[True, True, True],
        [True, True, True]])

In [145]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [146]:
torch.log(k)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [147]:
k.log()

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [148]:
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [149]:
k.exp()

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [150]:
k.sqrt()

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [151]:
k.sigmoid()

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [152]:
k.softmax(dim=0)

tensor([[9.1105e-04, 3.3535e-04, 4.7426e-02],
        [9.9909e-01, 9.9966e-01, 9.5257e-01]])

In [153]:
k.relu()

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [154]:
l=torch.rand(size=(2,3),dtype=torch.float32)
m=torch.rand(size=(2,3),dtype=torch.float32)
l,m

(tensor([[0.0874, 0.0041, 0.1088],
         [0.1637, 0.7025, 0.6790]]),
 tensor([[0.9155, 0.2418, 0.1591],
         [0.7653, 0.2979, 0.8035]]))

In [155]:
l+m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [156]:
l.add_(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [157]:
l

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [158]:
m

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])

In [159]:
l.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [160]:
n=m

In [161]:
id(m),id(n)

(134295877644944, 134295877644944)

In [162]:
n=m.clone()

In [163]:
id(m),id(n)

(134295877644944, 134295877644704)

In [164]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [165]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [166]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [167]:
b=torch.rand(2,3,4)
b

tensor([[[0.3813, 0.7860, 0.1115, 0.2477],
         [0.6524, 0.6057, 0.3725, 0.7980],
         [0.8399, 0.1374, 0.2331, 0.9578]],

        [[0.3313, 0.3227, 0.0162, 0.2137],
         [0.6249, 0.4340, 0.1371, 0.5117],
         [0.1585, 0.0758, 0.2247, 0.0624]]])

In [168]:
b.permute(2,0,1)

tensor([[[0.3813, 0.6524, 0.8399],
         [0.3313, 0.6249, 0.1585]],

        [[0.7860, 0.6057, 0.1374],
         [0.3227, 0.4340, 0.0758]],

        [[0.1115, 0.3725, 0.2331],
         [0.0162, 0.1371, 0.2247]],

        [[0.2477, 0.7980, 0.9578],
         [0.2137, 0.5117, 0.0624]]])

In [170]:
b.permute(2,1,0)

tensor([[[0.3813, 0.3313],
         [0.6524, 0.6249],
         [0.8399, 0.1585]],

        [[0.7860, 0.3227],
         [0.6057, 0.4340],
         [0.1374, 0.0758]],

        [[0.1115, 0.0162],
         [0.3725, 0.1371],
         [0.2331, 0.2247]],

        [[0.2477, 0.2137],
         [0.7980, 0.5117],
         [0.9578, 0.0624]]])

In [171]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [172]:
c=torch.rand(226,226,3)

In [173]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [174]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [175]:
d=torch.rand(1,20)
d.shape

torch.Size([1, 20])

In [176]:
d.squeeze(0).shape

torch.Size([20])

In [177]:
d=torch.rand(2,20)
d.shape

torch.Size([2, 20])

In [179]:
d.squeeze(0).shape

torch.Size([2, 20])

you have a tensor d with shape (2, 20) and you call d.squeeze(0), it will attempt to remove the dimension at index 0 if that dimension has a size of 1. However, in this case, the dimension at index 0 has a size of 2, not 1, so calling d.squeeze(0) will not change the shape of the tensor

In [180]:
import numpy as np

In [181]:
a=torch.tensor([1,2])

In [182]:
b=a.numpy()
type(b)

numpy.ndarray

In [183]:
c=np.array([1,2])
type(c)

numpy.ndarray

In [184]:
d=torch.from_numpy(c)
type(d)

torch.Tensor

# CUDA

In [185]:
import torch

In [ ]:
device=torch.device('cuda')

In [ ]:
torch.rand((2,3),device=device)

In [ ]:
a=torch.rand(2,3)
a

In [ ]:
b=a.to(device)

In [ ]:
b+5 #it performs in gpu

In [ ]:
import time
size=10000

matcpu1=torch.randn(size,size)
matcpu2=torch.randn(size,size)

starttime=time.time()
rescpu=torch.matmul(matcpu1,matcpu2)
cputime=time.time()-starttime

print(f'cpu : {cputime}')

matgpu1=matcpu1.to('cuda')
matgpu2=matcpu2.to('cuda')

starttime=time.time()
resgpu=torch.matmul(matgpu1,matgpu2)
torch.cuda.synchronize()
gputime=time.time()-starttime

print(f'cpu : {gputime}')

print(f'cpu/gpu : {cputime/gputime}')