In [1]:
import torch

In [12]:
torch.__version__

'2.4.1+cu121'

In [32]:
zero=torch.tensor([1])

In [33]:
zero.ndim

1

In [34]:
zero.ndimension()

1

In [35]:
zero.shape

torch.Size([1])

In [36]:
type(zero)

torch.Tensor

In [15]:
if torch.cuda.is_available():
    print(f'gpu :{torch.cuda.get_device_name(0)}')
else:
    print('cpu')

cpu


In [18]:
torch.empty(2,3)

tensor([[ 3.6532e+22,  4.4291e-41, -6.9121e+29],
        [ 3.1283e-41,  4.4842e-44,  0.0000e+00]])

In [21]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.rand(2,3)

tensor([[0.4962, 0.3388, 0.7675],
        [0.4599, 0.3279, 0.9521]])

In [25]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [31]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [30]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [66]:
single=torch.tensor([[1,2,3],[4,5,6]])

In [67]:
single

tensor([[1, 2, 3],
        [4, 5, 6]])

In [68]:
single.shape

torch.Size([2, 3])

In [69]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [71]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [72]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [73]:
torch.full((3,3),2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [74]:
torch.empty_like(single)

tensor([[7020674647234445312, 8319683848551211643, 3180222411935070754],
        [8391722768137527840, 7959390389040738153, 2318283120534233716]])

In [75]:
torch.zeros_like(single)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [76]:
torch.ones_like(single)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [87]:
torch.rand_like(single)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [88]:
torch.rand_like(single,dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [78]:
single.dtype

torch.int64

In [79]:
torch.tensor(single,dtype=torch.float32)

<ipython-input-79-8615d7b73341>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(single,dtype=torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [85]:
single.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [86]:
single.dtype

torch.int64

In [82]:
double=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]],dtype=torch.float32)

In [83]:
double

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [84]:
double.shape

torch.Size([2, 2, 2])

In [89]:
x=torch.rand(2,2)

In [90]:
x+2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [91]:
x-2

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

In [92]:
x*2

tensor([[1.7388, 1.1354],
        [1.4822, 0.8588]])

In [93]:
x/2

tensor([[0.4347, 0.2839],
        [0.3705, 0.2147]])

In [96]:
(x*100)//2

tensor([[43., 28.],
        [37., 21.]])

In [98]:
x%2

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [100]:
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

In [101]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [102]:
a+b

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])

In [103]:
a-b

tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])

In [104]:
a*b

tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])

In [105]:
a/b

tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])

In [106]:
a**b

tensor([[0.9645, 0.6301, 0.8700],
        [0.8820, 0.6248, 0.8495]])

In [107]:
a%b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [108]:
c=torch.tensor([-1,-2,-3,-4])

In [109]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [110]:
torch.neg(c)

tensor([1, 2, 3, 4])

In [111]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [112]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [113]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [114]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [115]:
torch.clamp(d,2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [141]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[0., 9., 6.],
        [9., 5., 4.]])

In [142]:
torch.sum(e)

tensor(33.)

In [143]:
torch.sum(e,dim=0)

tensor([ 9., 14., 10.])

In [144]:
torch.sum(e,dim=1)

tensor([15., 18.])

In [145]:
torch.mean(e)

tensor(5.5000)

In [146]:
torch.mean(e,0)

tensor([4.5000, 7.0000, 5.0000])

In [147]:
torch.median(e)

tensor(5.)

In [148]:
torch.max(e)

tensor(9.)

In [149]:
torch.max(e,0)

torch.return_types.max(
values=tensor([9., 9., 6.]),
indices=tensor([1, 0, 0]))

In [150]:
torch.prod(e)

tensor(0.)

In [151]:
torch.prod(e,0)

tensor([ 0., 45., 24.])

In [152]:
torch.std(e)

tensor(3.3912)

In [153]:
torch.var(e)

tensor(11.5000)

In [158]:
3.3912**2

11.50023744

In [155]:
torch.argmax(e)

tensor(1)

In [157]:
torch.argmax(e,0)

tensor([1, 0, 0])

In [159]:
torch.argmin(e)

tensor(0)

In [160]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
f,g

(tensor([[8, 8, 6],
         [0, 0, 0]]),
 tensor([[0, 1],
         [3, 0],
         [1, 1]]))

In [161]:
torch.matmul(f,g)

tensor([[30, 14],
        [ 0,  0]])

In [164]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])
vec1,vec2

(tensor([1, 2]), tensor([3, 4]))

In [163]:
torch.dot(vec1,vec2)

tensor(11)

In [165]:
torch.matmul(vec1,vec2)

tensor(11)

In [166]:
torch.transpose(f,0,1)

tensor([[8, 0],
        [8, 0],
        [6, 0]])

In [168]:
f.t()

tensor([[8, 0],
        [8, 0],
        [6, 0]])

In [175]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[1., 4., 1.],
        [6., 3., 2.],
        [0., 9., 8.]])

In [176]:
torch.det(h)

tensor(-132.)

In [177]:
torch.inverse(h)

tensor([[-0.0455,  0.1742, -0.0379],
        [ 0.3636, -0.0606, -0.0303],
        [-0.4091,  0.0682,  0.1591]])

In [178]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
i,j

(tensor([[5., 3., 7.],
         [7., 5., 9.]]),
 tensor([[1., 5., 1.],
         [9., 1., 4.]]))

In [179]:
i>j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [180]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [181]:
i>=j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [182]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 3., 7.],
        [5., 7., 1.]])

In [185]:
torch.log(k)

tensor([[  -inf, 1.0986, 1.9459],
        [1.6094, 1.9459, 0.0000]])

In [183]:
k.log()

tensor([[  -inf, 1.0986, 1.9459],
        [1.6094, 1.9459, 0.0000]])

In [186]:
torch.exp(k)

tensor([[1.0000e+00, 2.0086e+01, 1.0966e+03],
        [1.4841e+02, 1.0966e+03, 2.7183e+00]])

In [184]:
k.exp()

tensor([[1.0000e+00, 2.0086e+01, 1.0966e+03],
        [1.4841e+02, 1.0966e+03, 2.7183e+00]])

In [187]:
k.sqrt()

tensor([[0.0000, 1.7321, 2.6458],
        [2.2361, 2.6458, 1.0000]])

In [188]:
k.sigmoid()

tensor([[0.5000, 0.9526, 0.9991],
        [0.9933, 0.9991, 0.7311]])

In [190]:
k.softmax(dim=0)

tensor([[0.0067, 0.0180, 0.9975],
        [0.9933, 0.9820, 0.0025]])

In [191]:
k.relu()

tensor([[0., 3., 7.],
        [5., 7., 1.]])

In [193]:
l=torch.rand(size=(2,3),dtype=torch.float32)
m=torch.rand(size=(2,3),dtype=torch.float32)
l,m

(tensor([[0.2846, 0.2007, 0.5014],
         [0.3139, 0.4654, 0.1612]]),
 tensor([[0.1568, 0.2083, 0.3289],
         [0.1054, 0.9192, 0.4008]]))

In [194]:
l+m

tensor([[0.4414, 0.4090, 0.8302],
        [0.4193, 1.3846, 0.5620]])

In [196]:
l.add_(m)

tensor([[0.4414, 0.4090, 0.8302],
        [0.4193, 1.3846, 0.5620]])

In [197]:
l

tensor([[0.4414, 0.4090, 0.8302],
        [0.4193, 1.3846, 0.5620]])

In [198]:
m

tensor([[0.1568, 0.2083, 0.3289],
        [0.1054, 0.9192, 0.4008]])

In [199]:
l.relu_()

tensor([[0.4414, 0.4090, 0.8302],
        [0.4193, 1.3846, 0.5620]])

In [200]:
n=m

In [201]:
id(m),id(n)

(135749530969296, 135749530969296)

In [202]:
n=m.clone()

In [203]:
id(m),id(n)

(135749530969296, 135749530911664)

In [3]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [5]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b=torch.rand(2,3,4)
b

tensor([[[0.5311, 0.5834, 0.9360, 0.0399],
         [0.2072, 0.0033, 0.9307, 0.5337],
         [0.8486, 0.2175, 0.8196, 0.0233]],

        [[0.9373, 0.3293, 0.8735, 0.3137],
         [0.7391, 0.8795, 0.8829, 0.4920],
         [0.5769, 0.8834, 0.6471, 0.1644]]])

In [8]:
b.permute(2,0,1)

tensor([[[0.5311, 0.2072, 0.8486],
         [0.9373, 0.7391, 0.5769]],

        [[0.5834, 0.0033, 0.2175],
         [0.3293, 0.8795, 0.8834]],

        [[0.9360, 0.9307, 0.8196],
         [0.8735, 0.8829, 0.6471]],

        [[0.0399, 0.5337, 0.0233],
         [0.3137, 0.4920, 0.1644]]])

In [9]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [10]:
c=torch.rand(226,226,3)

In [12]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [13]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [15]:
d=torch.rand(1,20)
d.shape

torch.Size([1, 20])

In [17]:
d.squeeze(0).shape

torch.Size([20])

In [18]:
import numpy as np

In [19]:
a=torch.tensor([1,2])

In [22]:
b=a.numpy()
type(b)

numpy.ndarray

In [24]:
c=np.array([1,2])
type(c)

numpy.ndarray

In [25]:
d=torch.from_numpy(c)
type(d)

torch.Tensor

# CUDA

In [2]:
import torch

In [3]:
device=torch.device('cuda')

In [4]:
torch.rand((2,3),device=device)

tensor([[0.9908, 0.2758, 0.0149],
        [0.3923, 0.8502, 0.2495]], device='cuda:0')

In [6]:
a=torch.rand(2,3)
a

tensor([[0.9961, 0.9680, 0.8504],
        [0.9872, 0.0881, 0.3987]])

In [8]:
b=a.to(device)

In [9]:
b+5 #it performs in gpu

tensor([[5.9961, 5.9680, 5.8504],
        [5.9872, 5.0881, 5.3987]], device='cuda:0')

In [11]:
import time
size=10000

matcpu1=torch.randn(size,size)
matcpu2=torch.randn(size,size)

starttime=time.time()
rescpu=torch.matmul(matcpu1,matcpu2)
cputime=time.time()-starttime

print(f'cpu : {cputime}')

matgpu1=matcpu1.to('cuda')
matgpu2=matcpu2.to('cuda')

starttime=time.time()
resgpu=torch.matmul(matgpu1,matgpu2)
torch.cuda.synchronize()
gputime=time.time()-starttime

print(f'cpu : {gputime}')

print(f'cpu/gpu : {cputime/gputime}')

cpu : 9.405612468719482
cpu : 0.24215984344482422
cpu/gpu : 38.840512675102296
